apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 2  # Increased to 2 for redundancy
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-container
        image: divakars2005/html-app:latest  # Updated Docker Hub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Fixed NodePort for Minikube
  type: NodePort
